### ISSUE TITLE
Content-Type unset (or lacking control) on functions via watchdog

### ISSUE THREAD

**Issue by nkirsch** [alexellis/faas#45]
It isn't clear to me how to set the Content-Type on an individual function, particularly run via the fwatchdog.

## Expected Behavior

I should be able to write HTTP headers as part of the output of the program (like cgi-bin):

```
Content-Type: text/plain


hello world
```

Or specify it in the docker-compose:

```
   hello:
        image: functions/alpine:latest
        labels:
            function: "true"
        depends_on:
            - gateway
        networks:
            - functions
        environment:
            fprocess: "echo hello world"
            content_type: "text/plain"
            no_proxy: "gateway"
            https_proxy: $https_proxy
```

## Current Behavior
Content-Type appears to be unset when using `fwatchdog`.

## Possible Solution

1) static content_type in docker-compose
2) override_headers: "true"/"false" would allow the script to indicate http headers (via \n\n above)
3) headers_stderr: "true"/"false" override headers written to stderr

Happy to build something for PR if there is a desired direction.
