### ISSUE TITLE
API Gateway should scale (enhancement)

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#56]
The gateway could be a bottleneck in very high workloads. It should be able to scale.

## Current Behavior

Prometheus scraping would break

## Possible Solution

Add to prometheus.yml config:

```
  - job_name: "gateway"
    scrape_interval: 5s
    dns_sd_configs:
      - names: ['tasks.gateway']
        port: 8080
        type: A
        refresh_interval: 5s
```
