### ISSUE TITLE
Functions that run longer than 8 seconds return empty replies.

### ISSUE THREAD

**Issue by stealthybox** [alexellis/faas#94]
Long running functions (8+ seconds) return with empty responses.

## Expected Behavior
STDOUT should be returned in the response body.

## Current Behavior
The response body is empty.

## Steps to Reproduce
Deploy faas.
Create the following files:

#### func.yml
```yaml
version: '3.1'

services:
  test:
    image: functions/alpine
    networks: [ func_functions ]
    labels:
      function: 'true'
    environment:
      read_timeout: 60
      write_timeout: 60
      fprocess: 'sh /root/func.sh'
    volumes:
    -  .:/root
networks:
  func_functions:
    external: true
```
#### func.sh
```bash
DELAY=`cat -`
echo hi, sleeping for $DELAY
sleep $DELAY
echo done sleeping, bye!
```
This function takes a number as input and sleeps for that duration before responding.
Let's deploy it:
```bash
> docker deploy -c func.yml issue
> docker service logs -f issue_test
```
And curl the service to run for different lengths:
```bash
> time curl localhost:8089/function/issue_test -XPOST -d6
hi, sleeping for 6
done sleeping, bye!

real    0m6.013s
user    0m0.004s
sys     0m0.001s

> time curl localhost:8089/function/issue_test -XPOST -d7
hi, sleeping for 7
done sleeping, bye!

real    0m7.013s
user    0m0.000s
sys     0m0.006s

> time curl localhost:8089/function/issue_test -XPOST -d8
curl: (52) Empty reply from server

real    0m8.013s
user    0m0.000s
sys     0m0.005s

> time curl localhost:8089/function/issue_test -XPOST -d9
curl: (52) Empty reply from server

real    0m9.013s
user    0m0.002s
sys     0m0.003s

```
The test cases for 8 and 9 seconds still return a response, but the response is empty.

## Context
@cgpuglie and I are trying to run a web-scraper with nightmare-js as a faas function.
The runtime is variable, but typically longer than 8 seconds.

## Your Environment
```
> docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:29 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
